spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/uac
    username: uac_user
    password: F$#T$#TewfWR3%
    driverClassName: com.mysql.cj.jdbc.Driver

